#!/bin/bash

# Build the argument list from snap config
args=()

# add a `-option <value>`
add_option() {
    key=$1
    value="$(snapctl get "$key")"
    [ -n "$value" ] && args+=("-$key=$value")
}

# add a `-flag`
add_flag() {
    key=$1
    [ "$(snapctl get "$key")" = "true" ] && args+=("-$key")
}

add_option a
add_option hostname
add_option stun-port
add_flag verify-clients

# Hardcode the config file path, as it defaults to /var/lib/derper/derper.key otherwise.
# Also hardcode the tailscaled socket path; this path is present if the tailscale-socket plug is connected.
exec "${SNAP}/bin/derper" "-c=$SNAP_COMMON/derper.key" "-socket=$SNAP_DATA/tailscale-socket/tailscaled.sock" "${args[@]}"
