name: derper
summary: DERP Relay Server for Tailscale
description: |
  Self hosted DERP Relay servers for Tailscale networks. This snap provides a simple way to run your own DERP servers to route your tailscale traffic through your own relay servers.
  The following configuration options are currently supported.
  - hostname, defaults to `hostname -f`
  - verify-clients, defaults to true
  - stun-port
  - address
  Please refer to `derper -h` and the upstream documentation at https://tailscale.com/kb/1118/custom-derp-servers for explanations.
version: v1.58.2-1
grade: devel
base: core22

confinement: strict

layout:
  /var/lib/derper:
    bind: $SNAP_DATA/var/lib/derper

plugs:
  var-run-tailscale:
    interface: system-files
    read:
    - /run/tailscale/tailscaled.sock
    write:
    - /run/tailscale/tailscaled.sock

apps:
  derper-service:
    command: bin/derper-runner
    daemon: simple
    plugs:
      - network
      - network-bind
      - var-run-tailscale

  derper:
    command: bin/derper
    plugs:
      - network
      - network-bind
      - var-run-tailscale

parts:
  derper:
    plugin: go
    source-type: git
    source-tag: v1.58.2
    source: https://github.com/tailscale/tailscale/
    build-snaps:
    - go
    override-build: | 
      go mod download all
      go install -p $CRAFT_PARALLEL_BUILD_COUNT ./cmd/derper
  files:
    plugin: dump
    source: .
